### ISSUE TITLE
Can we use this library in a Java project?

### ISSUE THREAD

**Issue by gajendravaradhan** [G-Research/spark-extension#31]
Can we use this library, specifically the diff in java. Right now when I import the dependency and do a diff on an expected vs actual data sets, the diff is not getting recognized as amethod.

Below is the method signature I am using this on:
![image](https://user-images.githubusercontent.com/5377342/105895957-33224c00-5fe4-11eb-9bbf-308899f0dbb4.png)

I have imported the package as : 
`import uk.co.gresearch.spark.diff.*;`

**Comment by EnricoMi** [comment]
That is very good question. I planned to look into this but haven't got around it. See issue #11 for updates on this.

The `Dataset<T>.diff(Dataset<T>, String... columns)` method in particular is not available in Java because this is provided through an implicit class, which is not compatible to Java. However, you can use the `Diff` static class.

```java
Diff$.MODULE$.of(expected, actual, primaryKey1, primaryKey2).show();
```
That is the easiest way to access the API.

For a single key as in your example, things already get complicated:
```java
List<String> primaryKeyList = Collections.singletonList(primaryKey);
Seq<String> primaryKeySeq = JavaConverters.asScalaIteratorConverter(primaryKeyList.iterator()).asScala().toSeq();
Diff$.MODULE$.of(expected, actual, primaryKeySeq).show();
```

If you want to modify the diffing, you can create `DiffOptions` and `Diff` instances:

```java
DiffOptions options = new DiffOptions(
  "diff",
  "left", "right",
  "I", "C", "D", "N",
  scala.Option.apply(null),
  DiffMode.ColumnByColumn(),
  false
);

Dataset<Row> diff = new Diff(options).of(left, right, primaryKeySeq);
diff.show();
```

The Scala API will see some improvement in the future so that it become easier to use it in Java.

**Comment by EnricoMi** [comment]
A proper Java API has been released in 1.4.0 and 2.0.0. You can diff in Java as:

    import uk.co.gresearch.spark.diff.Diff;

    Dataset<Row> diff = Diff.of(left, right);

See `src/test/java/uk/co/gresearch/spark/diff/DiffJavaTests.java` for more Java examples.

Please give it a try.

**Comment by gajendravaradhan** [comment]
@EnricoMi - Just tested it out and it works like a charm. One suggestion, when trying to write a diff report to a flat file, I am not able to write it with the changes column since it uses Array data structure. Can it be modified to contain a delimited set of column names instead of an array.

**Comment by EnricoMi** [comment]
I am glad it works for you, thanks for reporting.

You could turn the array of strings into a string before writing to CSV, e.g. by concatenating the values using a seperator token: https://sparkbyexamples.com/spark/spark-convert-array-string-to-string-column/
